version: '3.7'

services:
  minimalism-service-active-campaign:
    container_name: minimalism-service-active-campaign
    image: carlonicora/php-cli-base:7.4.3.2
    working_dir: /app
    volumes:
      - ../:/app
      - ../:/opt/project
    tty: true
    stdin_open: true
    networks:
      - default_network

networks:
  default_network:
    driver: bridge
    name: carlonicora