version: '3.8'

services:
  minimalism-service-active-campaign:
    container_name: minimalism-service-active-campaign
    image: phlow/minimalism-service-active-campaign:3.0
    build:
      context: .
      dockerfile: ./php-cli/Dockerfile
    working_dir: /app
    volumes:
      - ../:/app
    tty: true
    stdin_open: true
    networks:
      - default_network

networks:
  default_network:
    driver: bridge
    name: phlow